AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Rails:
  Enabled: true

RegexpLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 120
