version: '3.0'
services:
  es6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    container_name: es6
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata6:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  esdata6:
    driver: local

networks:
  esnet:
